# Auto-generated from the Claude-artifact question bank. Do not hand-edit — regenerate instead.
# options[0] is always the CORRECT answer; the API shuffles per-attempt before sending to clients.

TOPIC_LABELS = {'ECO': 'Cloud Ecosystem',
 'CON': 'Concepts & Models',
 'CHAR': 'Key Characteristics',
 'READY': 'Readiness & Resource Mgmt',
 'OUT': 'Outsourcing & Vendors',
 'CFG': 'Cloud Configuration',
 'ARCH': 'Architecture & Storage',
 'TREND': 'Trends',
 'RISK': 'Risks & Mitigation'}

QUESTIONS = [{'id': 1,
  'section': 'A',
  'topic': 'ECO',
  'stem': 'Which of the following is generally considered a core element of the cloud ecosystem?',
  'options': ['Cloud service providers',
              'Physical filing cabinets',
              'Fax machines',
              'Paper-based ledgers']},
 {'id': 2,
  'section': 'A',
  'topic': 'ECO',
  'stem': 'Cloud consumers are best described as:',
  'options': ['Organizations or individuals who use cloud services',
              'Companies that manufacture servers only',
              'Government regulators of the internet',
              'Hardware repair technicians']},
 {'id': 3,
  'section': 'A',
  'topic': 'ECO',
  'stem': "A cloud service broker's main role is to:",
  'options': ['Help match consumers with the right cloud services and manage relationships between '
              'providers and consumers',
              'Physically install servers on-site',
              'Write firmware for network routers',
              'Approve government tenders']},
 {'id': 4,
  'section': 'A',
  'topic': 'ECO',
  'stem': 'Which element of the cloud ecosystem ensures services meet agreed performance and '
          'availability levels?',
  'options': ['Service Level Agreements (SLAs)',
              'Marketing department',
              'End-user manuals',
              'Office furniture supplier']},
 {'id': 5,
  'section': 'A',
  'topic': 'ECO',
  'stem': 'Cloud auditors primarily exist to:',
  'options': ['Independently assess cloud service performance, security, and compliance',
              'Design company logos',
              'Manage payroll',
              'Sell hardware']},
 {'id': 6,
  'section': 'A',
  'topic': 'ECO',
  'stem': 'Which of these is NOT typically considered a key element of the cloud ecosystem?',
  'options': ['Postal courier service', 'Cloud carrier', 'Cloud provider', 'Cloud consumer']},
 {'id': 7,
  'section': 'A',
  'topic': 'CON',
  'stem': 'According to NIST, cloud computing is best defined as:',
  'options': ['A model enabling on-demand network access to a shared pool of configurable '
              'computing resources',
              'A single dedicated server owned by one company',
              'A type of physical data cable',
              'A method of manually backing up files to USB drives']},
 {'id': 8,
  'section': 'A',
  'topic': 'CON',
  'stem': 'Which term describes computing resources being available to users without requiring '
          'human interaction with the provider?',
  'options': ['On-demand self-service', 'Manual provisioning', 'Vendor lock-in', 'Cold storage']},
 {'id': 9,
  'section': 'A',
  'topic': 'CON',
  'stem': 'Infrastructure as a Service (IaaS) primarily provides:',
  'options': ['Virtualized computing resources such as servers, storage, and networking',
              'Fully built and managed applications only',
              'Only a development platform with no infrastructure',
              'Physical office space']},
 {'id': 10,
  'section': 'A',
  'topic': 'CON',
  'stem': 'Platform as a Service (PaaS) is best suited for:',
  'options': ['Developers who want to build and deploy applications without managing underlying '
              'infrastructure',
              'End users who only need email access',
              'Companies wanting to buy physical servers',
              'Organizations with no internet access']},
 {'id': 11,
  'section': 'A',
  'topic': 'CON',
  'stem': 'Software as a Service (SaaS) is an example of:',
  'options': ['Fully hosted applications delivered over the internet, e.g. webmail or CRM tools',
              'Renting raw compute and storage',
              'A private in-house server room',
              'On-premises hardware installation']},
 {'id': 12,
  'section': 'A',
  'topic': 'CON',
  'stem': 'A Public Cloud deployment model means:',
  'options': ['Resources are owned and operated by a third-party provider and shared among '
              'multiple organizations',
              'Resources are used exclusively by one organization on its own premises',
              'There is no internet connectivity involved',
              'Only government agencies can use it']},
 {'id': 13,
  'section': 'A',
  'topic': 'CON',
  'stem': 'A Private Cloud deployment model is best described as:',
  'options': ['Infrastructure provisioned for exclusive use by a single organization',
              'A cloud shared openly with the general public',
              'A cloud with no security controls',
              'A model with no scalability']},
 {'id': 14,
  'section': 'A',
  'topic': 'CON',
  'stem': 'A Hybrid Cloud combines:',
  'options': ['Public and private cloud environments, allowing data and applications to move '
              'between them',
              'Only on-premises servers',
              'Two public clouds from different vendors',
              'Paper records and digital records']},
 {'id': 15,
  'section': 'A',
  'topic': 'CON',
  'stem': 'In cloud deployment, "federation" refers to:',
  'options': ['The ability to integrate and manage identities and resources across multiple cloud '
              'environments',
              'Deleting unused virtual machines',
              'Physically relocating a data center',
              'Turning off cloud services permanently']},
 {'id': 16,
  'section': 'A',
  'topic': 'CON',
  'stem': '"Automation" in cloud deployment enables:',
  'options': ['Provisioning and management of resources without manual intervention',
              'Manual ticket logging only',
              'Increased paperwork',
              'Slower deployment cycles']},
 {'id': 17,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Rapid elasticity" in cloud computing refers to:',
  'options': ['The ability to scale resources up or down quickly based on demand',
              'Fixed, unchangeable resource allocation',
              'Slow annual capacity planning only',
              'Manual hardware replacement']},
 {'id': 18,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Measured service" means:',
  'options': ['Resource usage is monitored, controlled, and billed based on consumption',
              'All services are provided for free',
              'Usage cannot be tracked',
              'Only physical meters are used']},
 {'id': 19,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Broad network access" means cloud services are:',
  'options': ['Accessible over standard networks like the internet from various devices',
              'Only accessible from one specific device',
              'Available only within a single building',
              'Restricted to landline phones']},
 {'id': 20,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Resource pooling" describes:',
  'options': ['Multiple customers sharing provider resources, dynamically assigned as needed',
              'Each customer owning a dedicated physical server permanently',
              'Resources never being reassigned',
              'Pooling of office supplies']},
 {'id': 21,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Multitenancy" allows:',
  'options': ['Multiple users to share the same infrastructure while keeping their data isolated',
              'Only one user per server at all times',
              'Users to physically share the same keyboard',
              'Data to be merged between different customers']},
 {'id': 22,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Device and location independence" means users can:',
  'options': ['Access cloud services from any device and location with internet access',
              'Only use company-issued devices',
              'Only access services from the data center',
              'Not use mobile devices at all']},
 {'id': 23,
  'section': 'A',
  'topic': 'CHAR',
  'stem': '"Centralized performance monitoring" in the cloud helps:',
  'options': ['Track availability and health of services from a single point of control',
              'Replace the need for any monitoring',
              'Increase downtime',
              'Eliminate the need for SLAs']},
 {'id': 24,
  'section': 'A',
  'topic': 'CHAR',
  'stem': 'Improved business continuity and disaster recovery in the cloud is mainly achieved '
          'through:',
  'options': ['Redundant, distributed infrastructure that allows quick recovery from failures',
              'Storing all backups on a single local hard drive',
              'Avoiding any data replication',
              'Relying solely on paper records']},
 {'id': 25,
  'section': 'A',
  'topic': 'READY',
  'stem': '"Cloud readiness" can best be defined as:',
  'options': ["An organization's preparedness — technically, financially, and culturally — to "
              'adopt cloud solutions',
              'The physical size of a server room',
              'The number of employees a company has',
              "The age of a company's website"]},
 {'id': 26,
  'section': 'A',
  'topic': 'READY',
  'stem': 'Which of the following is a POSITIVE indicator that a business should adopt cloud '
          'solutions?',
  'options': ['A need for scalable infrastructure to handle variable workloads',
              'Strict regulations that forbid any data leaving on-premises servers',
              'No internet connectivity at any site',
              'Zero budget for IT changes']},
 {'id': 27,
  'section': 'A',
  'topic': 'READY',
  'stem': 'Which of the following is a NEGATIVE indicator against cloud adoption?',
  'options': ['Severe data sovereignty restrictions preventing off-site data storage',
              'A growing need for remote collaboration',
              'Fluctuating demand for compute resources',
              'A desire to reduce hardware capital expenditure']},
 {'id': 28,
  'section': 'A',
  'topic': 'READY',
  'stem': 'Good resource management in cloud computing is important primarily because it:',
  'options': ['Ensures resources are used efficiently, controlling costs and maintaining '
              'performance',
              'Increases unnecessary spending',
              'Has no impact on service quality',
              'Prevents any scaling of resources']},
 {'id': 29,
  'section': 'A',
  'topic': 'READY',
  'stem': 'One of the principles of cloud resource management is:',
  'options': ['Load balancing — distributing workloads evenly across resources',
              'Ignoring demand fluctuations',
              'Permanently fixed allocation with no monitoring',
              'Manual-only provisioning with no automation']},
 {'id': 30,
  'section': 'A',
  'topic': 'OUT',
  'stem': 'A key difference between cloud computing and traditional outsourcing is:',
  'options': ['Cloud computing typically offers on-demand, self-service access, while outsourcing '
              'often involves longer-term contracted arrangements',
              'Outsourcing always uses shared infrastructure',
              'Cloud computing never involves a third party',
              'There is no difference at all']},
 {'id': 31,
  'section': 'A',
  'topic': 'OUT',
  'stem': 'A similarity between cloud computing and outsourcing is that both:',
  'options': ['Involve relying on an external party to provide a service or capability',
              'Always require on-premises hardware',
              'Are free of any contractual agreement',
              'Cannot be scaled']},
 {'id': 32,
  'section': 'A',
  'topic': 'OUT',
  'stem': 'Which of the following is a typical role of a cloud computing vendor?',
  'options': ['Providing infrastructure, platforms, or software as a service to customers',
              'Manufacturing office furniture',
              'Regulating national tax policy',
              'Running unrelated retail stores']},
 {'id': 33,
  'section': 'A',
  'topic': 'OUT',
  'stem': 'A common concern (dependency) when engaging with cloud vendors is:',
  'options': ['Vendor lock-in, making it difficult to switch providers',
              'Guaranteed zero cost forever',
              'Complete elimination of all business risk',
              'No need for a contract']},
 {'id': 34,
  'section': 'A',
  'topic': 'OUT',
  'stem': 'A mitigation strategy to avoid vendor dependency is:',
  'options': ['Using open standards and multi-cloud strategies to maintain portability',
              'Committing exclusively to one proprietary, closed platform',
              'Avoiding all documentation of configurations',
              'Refusing to negotiate contract terms']},
 {'id': 35,
  'section': 'A',
  'topic': 'CFG',
  'stem': 'In cloud configuration, "hardware" refers to:',
  'options': ['The physical computing equipment such as servers, storage devices, and networking '
              'equipment',
              'The operating system only',
              'A set of business processes',
              'Marketing collateral']},
 {'id': 36,
  'section': 'A',
  'topic': 'CFG',
  'stem': 'Which of the following is a component of hardware in a cloud environment?',
  'options': ['Storage devices',
              'Operating system license',
              'API documentation',
              'Service level agreement']},
 {'id': 37,
  'section': 'A',
  'topic': 'CFG',
  'stem': '"Software" in a cloud environment refers to:',
  'options': ['Programs and operating systems that run on hardware to perform tasks',
              'Physical network cables',
              'Data center cooling systems',
              'Power supply units']},
 {'id': 38,
  'section': 'A',
  'topic': 'CFG',
  'stem': 'Which is an example of a "service" in cloud configuration?',
  'options': ['Managed database service',
              'A physical server rack',
              'An ethernet cable',
              'A power generator']},
 {'id': 39,
  'section': 'A',
  'topic': 'CFG',
  'stem': 'Interoperability between hardware, software, and services in the cloud matters because '
          'it:',
  'options': ['Ensures the different layers work together smoothly for the cloud environment to '
              'function effectively',
              'Prevents any communication between components',
              'Is only relevant for on-premises systems',
              'Has no effect on system performance']},
 {'id': 40,
  'section': 'A',
  'topic': 'ARCH',
  'stem': 'A "Region" in cloud architecture refers to:',
  'options': ['A geographical area where a cloud provider hosts a cluster of data centers',
              'A single physical server',
              'A type of storage device',
              'A network cable']},
 {'id': 41,
  'section': 'A',
  'topic': 'ARCH',
  'stem': 'An "Availability Zone" (AZ) is best described as:',
  'options': ['A physically separate data center within a region, with independent power and '
              'networking',
              "The entire cloud provider's global network",
              'A single virtual machine',
              'A type of firewall rule']},
 {'id': 42,
  'section': 'A',
  'topic': 'ARCH',
  'stem': '"Virtualization" in cloud computing is:',
  'options': ['The process of creating virtual versions of physical resources like servers and '
              'storage',
              'Physically duplicating hardware',
              'Deleting unused files',
              'A type of encryption algorithm']},
 {'id': 43,
  'section': 'A',
  'topic': 'ARCH',
  'stem': 'A "bare metal server" refers to:',
  'options': ['A physical server without a virtualization layer, offering direct hardware access',
              'A fully virtualized cloud instance',
              'A type of cloud storage',
              'A software application']},
 {'id': 44,
  'section': 'A',
  'topic': 'ARCH',
  'stem': 'Object storage is best described as a storage system that:',
  'options': ['Stores data as discrete units called objects, each with metadata and a unique '
              'identifier',
              'Only stores data in a strict folder hierarchy like a traditional file system',
              'Cannot store metadata',
              'Is limited to text files only']},
 {'id': 45,
  'section': 'A',
  'topic': 'ARCH',
  'stem': '"Persistent storage" in the cloud is characterized by:',
  'options': ['Data remaining available even after the associated compute instance is stopped or '
              'terminated',
              'Data being permanently deleted when a VM restarts',
              'Data existing only in RAM',
              'Data being inaccessible after saving']},
 {'id': 46,
  'section': 'A',
  'topic': 'TREND',
  'stem': '"Cloud native" applications are designed to:',
  'options': ['Be built and optimized specifically to run in cloud environments for scalability '
              'and resilience',
              'Only run on physical mainframes',
              'Avoid using the internet',
              'Work exclusively offline']},
 {'id': 47,
  'section': 'A',
  'topic': 'TREND',
  'stem': '"Serverless computing" means:',
  'options': ['The cloud provider manages the underlying infrastructure so developers can focus on '
              'code without managing servers',
              'There are no servers involved anywhere in the process',
              "Applications run only on the user's local device",
              'Developers must manually configure every server']},
 {'id': 48,
  'section': 'A',
  'topic': 'TREND',
  'stem': 'A "microservices" architecture involves:',
  'options': ['Building an application as a collection of small, independent services that '
              'communicate via APIs',
              'Building one large monolithic application with no separation of components',
              'Avoiding APIs entirely',
              'Running everything as a single process with no modularity']},
 {'id': 49,
  'section': 'A',
  'topic': 'RISK',
  'stem': 'A common technical challenge related to "application performance" in the cloud is:',
  'options': ['Latency caused by network distance or resource contention',
              'Guaranteed zero latency at all times',
              'Complete immunity to slowdowns',
              'No dependency on network conditions']},
 {'id': 50,
  'section': 'A',
  'topic': 'RISK',
  'stem': 'A best practice to mitigate network security risk in the cloud includes:',
  'options': ['Implementing strong encryption and access controls',
              'Disabling all firewalls',
              'Sharing admin credentials openly',
              'Avoiding any monitoring of traffic']},
 {'id': 51,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A startup wants to rent virtual machines, storage, and networking, but wants full '
          'control over the operating system and installed software. Which service model should '
          'they choose?',
  'options': ['Infrastructure as a Service (IaaS)',
              'Software as a Service (SaaS)',
              'Platform as a Service (PaaS)',
              'Function as a Service only']},
 {'id': 52,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A development team wants to focus purely on writing code and deploying applications, '
          'without worrying about patching operating systems or provisioning servers. Which '
          'service model best fits?',
  'options': ['Platform as a Service (PaaS)',
              'Infrastructure as a Service (IaaS)',
              'On-premises hosting',
              'Bare metal hosting']},
 {'id': 53,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A small business wants to use an email and collaboration suite without installing or '
          'maintaining any software locally. Which service model is most appropriate?',
  'options': ['Software as a Service (SaaS)',
              'Infrastructure as a Service (IaaS)',
              'Platform as a Service (PaaS)',
              'Bare metal servers']},
 {'id': 54,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A financial institution is legally required to keep certain sensitive data entirely '
          'on-premises, but wants to burst additional workloads into the cloud during peak '
          'periods. Which deployment model fits best?',
  'options': ['Hybrid Cloud',
              'Public Cloud only',
              'Community Cloud only',
              'Private Cloud only, with no cloud bursting']},
 {'id': 55,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A government department wants exclusive, dedicated infrastructure not shared with any '
          'other organization, prioritizing control and compliance over cost savings. Which '
          'deployment model should they choose?',
  'options': ['Private Cloud', 'Public Cloud', 'Hybrid Cloud', 'Multi-tenant shared cloud']},
 {'id': 56,
  'section': 'B',
  'topic': 'CON',
  'stem': "A media streaming company wants the lowest possible cost and doesn't mind sharing "
          "infrastructure with other tenants, since their workloads aren't subject to strict "
          'regulatory constraints. Which deployment model is most cost-effective?',
  'options': ['Public Cloud',
              'Private Cloud',
              'On-premises only',
              'Hybrid Cloud with heavy private allocation']},
 {'id': 57,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A company wants different cloud environments (from different providers or business '
          'units) to share identity management so users can access resources across all of them '
          'seamlessly. Which technique addresses this?',
  'options': ['Federation', 'Bare metal provisioning', 'Object storage', 'Manual ticketing']},
 {'id': 58,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A company wants to reduce manual configuration errors and speed up provisioning of new '
          'environments across teams. Which technique should they implement?',
  'options': ['Automation',
              'Federation',
              'Standardization only, with no tooling',
              'Manual change requests']},
 {'id': 59,
  'section': 'B',
  'topic': 'CON',
  'stem': 'An enterprise operating across multiple cloud providers wants consistent security '
          'policies, naming conventions, and compliance practices across all environments. Which '
          'practice addresses this?',
  'options': ['Standardization',
              'Vendor lock-in',
              'Manual override of all policies',
              'Random configuration per team']},
 {'id': 60,
  'section': 'B',
  'topic': 'CON',
  'stem': 'A retail company wants store managers to request and provision their own virtual '
          'servers for short-term promotions, without IT approval for each request. Which '
          'capability enables this?',
  'options': ['Self-service provisioning',
              'Manual procurement process',
              'Vendor lock-in',
              'Federation only']},
 {'id': 61,
  'section': 'B',
  'topic': 'CHAR',
  'stem': "During a major sales event, a company's website traffic spikes to 10x normal levels for "
          'six hours, then returns to normal. Which cloud characteristic lets the infrastructure '
          'handle this automatically?',
  'options': ['Rapid elasticity',
              'Fixed provisioning',
              'Vendor lock-in',
              'Bare metal-only hosting']},
 {'id': 62,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'A finance department wants to be billed only for the exact compute hours and storage GB '
          'they actually consume each month. Which characteristic supports this?',
  'options': ['Measured service',
              'Flat-rate licensing',
              'Resource pooling only',
              'Device independence']},
 {'id': 63,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'Employees need to securely access company applications from laptops, tablets, and '
          'phones, in the office and while traveling. Which characteristic supports this?',
  'options': ['Broad network access and device independence',
              'Bare metal servers',
              'Manual provisioning',
              'Vendor lock-in']},
 {'id': 64,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'A SaaS provider serves thousands of customers from the same application instance while '
          "keeping each customer's data logically separated. This is an example of:",
  'options': ['Multitenancy', 'Single-tenancy', 'On-premises hosting', 'Federation']},
 {'id': 65,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'An IT manager wants one dashboard to track uptime, response time, and resource health '
          'across all cloud services. This need is addressed by:',
  'options': ['Centralized performance monitoring',
              'Manual spreadsheet tracking only',
              'Vendor lock-in',
              'Object storage']},
 {'id': 66,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'A company survives a regional data center outage because workloads automatically failed '
          'over to another availability zone. This demonstrates:',
  'options': ['Improved business continuity and disaster recovery',
              'Poor resource pooling',
              'Lack of elasticity',
              'Vendor lock-in']},
 {'id': 67,
  'section': 'B',
  'topic': 'CHAR',
  'stem': 'A company stops purchasing and maintaining physical servers, instead paying variable '
          'costs based on usage. This reflects:',
  'options': ['Hardware independence and variable cost',
              'Fixed capital expenditure only',
              'Manual patching requirements',
              'Device dependency']},
 {'id': 68,
  'section': 'B',
  'topic': 'READY',
  'stem': 'A business has fluctuating, unpredictable workloads, wants to reduce upfront capital '
          'expenditure, and has strong executive buy-in for digital transformation. Based on '
          'readiness indicators, this business is:',
  'options': ['A strong candidate for cloud adoption',
              'A poor candidate, since fluctuating workloads are a negative indicator',
              'Unable to use cloud services under any circumstances',
              'Required to stay fully on-premises regardless of need']},
 {'id': 69,
  'section': 'B',
  'topic': 'READY',
  'stem': 'A business operates in a highly regulated industry with strict data residency laws '
          'forbidding data leaving the country, and has no cloud-skilled staff. Based on readiness '
          'indicators, this business should:',
  'options': ['Proceed cautiously, closing regulatory and skills gaps before adopting cloud, or '
              'consider in-country cloud options',
              'Migrate everything to public cloud immediately with no planning',
              'Ignore data residency laws',
              'Treat this as irrelevant to cloud readiness']},
 {'id': 70,
  'section': 'B',
  'topic': 'READY',
  'stem': 'Which organizational capability is most critical for a business to realize the full '
          'benefits of cloud computing?',
  'options': ['Strong governance and change management processes',
              'A large physical warehouse',
              'An in-house server manufacturing unit',
              'No IT staff at all']},
 {'id': 71,
  'section': 'B',
  'topic': 'READY',
  'stem': 'A resource management strategy that dynamically shifts workloads across servers to '
          'prevent any single server from being overwhelmed applies the principle of:',
  'options': ['Load balancing', 'Static allocation', 'Vendor lock-in', 'Manual escalation only']},
 {'id': 72,
  'section': 'B',
  'topic': 'READY',
  'stem': 'A cloud team continuously analyzes usage patterns and rightsizes resources (e.g. '
          'downgrading underused VMs) to control costs. This reflects which principle?',
  'options': ['Resource optimization',
              'Ignoring utilization data',
              'Permanent over-provisioning',
              'Manual paper tracking']},
 {'id': 73,
  'section': 'B',
  'topic': 'OUT',
  'stem': 'A company signs a long-term contract with a single cloud vendor and later finds it '
          'prohibitively expensive and technically difficult to migrate away, even though better '
          'options exist. This illustrates:',
  'options': ['Vendor lock-in', 'Federation', 'Rapid elasticity', 'Resource pooling']},
 {'id': 74,
  'section': 'B',
  'topic': 'OUT',
  'stem': 'To reduce dependency risk on a single cloud vendor, an organization designs '
          'applications using open, portable technologies and runs workloads across two providers. '
          'This strategy is known as:',
  'options': ['Multi-cloud strategy',
              'Single-vendor commitment',
              'Manual failover only',
              'Standard outsourcing']},
 {'id': 75,
  'section': 'B',
  'topic': 'OUT',
  'stem': 'When evaluating a potential cloud vendor, an organization assesses financial stability, '
          'security certifications, and support SLAs. This primarily addresses:',
  'options': ['Vendor dependency and risk management',
              'Office furniture procurement',
              'Marketing strategy',
              'Product packaging']},
 {'id': 76,
  'section': 'B',
  'topic': 'OUT',
  'stem': 'Outsourcing an IT helpdesk to a firm on a five-year fixed contract, versus using a '
          "cloud provider's pay-as-you-go service, illustrates the key difference of:",
  'options': ['Contract duration and flexibility of engagement',
              'Both being identical in every respect',
              'Outsourcing always being cheaper',
              'Cloud computing always requiring a five-year contract']},
 {'id': 77,
  'section': 'B',
  'topic': 'OUT',
  'stem': 'Which of the following is a role a cloud vendor should typically play for its '
          'customers?',
  'options': ['Providing ongoing technical support and maintaining service uptime per the SLA',
              "Setting the customer's internal HR policies",
              "Managing the customer's unrelated retail operations",
              "Approving the customer's tax filings"]},
 {'id': 78,
  'section': 'B',
  'topic': 'CFG',
  'stem': 'Cloud virtual machines are running fine, but the application installed on them keeps '
          'crashing due to an unsupported OS patch. This is primarily an issue with which layer?',
  'options': ['Software', 'Hardware', 'Networking cables', 'Physical data center cooling']},
 {'id': 79,
  'section': 'B',
  'topic': 'CFG',
  'stem': 'Servers (hardware) are functioning correctly and the OS (software) is stable, but users '
          "can't access a managed database because the service layer is misconfigured. This shows "
          'why cloud environments require:',
  'options': ['Interoperability between hardware, software, and services',
              'Hardware alone, with no software or services',
              'Complete separation with no communication between layers',
              'Elimination of all services']},
 {'id': 80,
  'section': 'B',
  'topic': 'CFG',
  'stem': 'Which of the following best represents the "services" layer of cloud configuration '
          '(versus hardware or software)?',
  'options': ['A managed backup-as-a-service offering',
              'A physical hard drive',
              'An operating system kernel',
              'A network switch']},
 {'id': 81,
  'section': 'B',
  'topic': 'CFG',
  'stem': 'A company configuring its cloud environment must decide on storage devices, compute '
          'nodes, and network equipment. Which layer are they working with?',
  'options': ['Hardware', 'Software', 'Services', 'None of the above']},
 {'id': 82,
  'section': 'B',
  'topic': 'CFG',
  'stem': 'A cloud provider updates its hypervisor without informing customers, causing '
          'compatibility issues with customer applications. This highlights the importance of:',
  'options': ['Interoperability and communication between hardware, software, and services',
              'Ignoring vendor updates entirely',
              'Avoiding the use of hypervisors',
              'Eliminating all software layers']},
 {'id': 83,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A company wants its application to stay available even if an entire facility loses '
          'power, so it deploys resources across two separate facilities within the same region, '
          'each with independent power and networking. What are they using?',
  'options': ['Multiple Availability Zones',
              'A single bare metal server',
              'One data center only',
              'Ephemeral storage only']},
 {'id': 84,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A global company wants to reduce latency for users in Europe, Asia, and North America '
          'by hosting resources close to each user base. Which concept should they leverage?',
  'options': ['Multiple Regions',
              'A single Availability Zone',
              'One centralized data center',
              'Object storage only']},
 {'id': 85,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'An administrator needs to run multiple isolated operating systems on one physical '
          'server to maximize hardware utilization. Which technology enables this?',
  'options': ['Virtualization (via a hypervisor)',
              'Bare metal provisioning',
              'Object storage',
              'Direct attached storage']},
 {'id': 86,
  'section': 'B',
  'topic': 'ARCH',
  'stem': "A hypervisor that runs directly on the host's hardware, with no underlying host "
          'operating system required, is known as:',
  'options': ['A Type 1 (bare-metal) hypervisor',
              'A Type 2 (hosted) hypervisor',
              'A software container',
              'A network switch']},
 {'id': 87,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A hypervisor that runs as an application on top of an existing operating system (e.g. a '
          'developer testing VMs on their laptop) is known as:',
  'options': ['A Type 2 (hosted) hypervisor',
              'A Type 1 (bare-metal) hypervisor',
              'A physical server',
              'A storage array']},
 {'id': 88,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A company needs extremely high, direct performance for a specialized workload and a '
          'licensing requirement forbids virtualization, so it runs the workload with no '
          'hypervisor layer. Which option is this?',
  'options': ['Bare metal server',
              'Virtual machine',
              'Container on shared hardware',
              'Serverless function']},
 {'id': 89,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A company migrating a large, sensitive on-premises database to the cloud wants to '
          'minimize downtime by replicating data continuously before final cutover. Which '
          'migration approach is this?',
  'options': ['Continuous/incremental replication migration',
              'One-time manual file copy with no testing',
              'Deleting the source data before starting',
              'Ignoring data validation']},
 {'id': 90,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A media company needs to store millions of unstructured video files, each accessed via '
          'a unique URL, with rich metadata attached. Which storage type is most appropriate?',
  'options': ['Object storage', 'Block storage', 'Ephemeral storage', 'Bare metal storage']},
 {'id': 91,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A database requires low-latency, high-performance storage that behaves like a raw disk '
          'directly attached to the VM. Which storage type fits best?',
  'options': ['Block storage',
              'Object storage',
              'Ephemeral/direct-attached storage only',
              'File storage']},
 {'id': 92,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A team needs a shared network drive that multiple VMs can mount simultaneously using '
          'standard protocols (NFS/SMB). Which storage type should they use?',
  'options': ['File storage', 'Block storage', 'Object storage', 'Bare metal storage']},
 {'id': 93,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A temporary cache used by an application, expected to be lost if the VM is stopped, is '
          'best described as:',
  'options': ['Direct attached/ephemeral storage',
              'Persistent storage',
              'Object storage',
              'File storage']},
 {'id': 94,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'A company needs data to remain intact even after the VM instance using it is deleted '
          'and recreated. Which storage type should they use?',
  'options': ['Persistent storage', 'Ephemeral storage', 'Temporary cache', 'RAM-only storage']},
 {'id': 95,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'Which cloud architecture component connects resources within and across regions, AZs, '
          'and data centers using virtual networks, subnets, and routing?',
  'options': ['Networking', 'Virtualization', 'Object storage', 'Bare metal']},
 {'id': 96,
  'section': 'B',
  'topic': 'ARCH',
  'stem': 'An app hosted in one Availability Zone went down when that facility lost power, while a '
          "competitor's app (spread across three AZs) stayed online. What should the architect "
          'recommend?',
  'options': ['Deploying across multiple Availability Zones for redundancy',
              'Moving everything to a single bare metal server',
              'Removing all backups',
              'Avoiding the use of regions entirely']},
 {'id': 97,
  'section': 'B',
  'topic': 'TREND',
  'stem': 'A company wants to combine its on-premises private cloud with resources from multiple '
          'public cloud providers, avoiding dependency on any single vendor while optimizing cost '
          'and performance. Which trend describes this?',
  'options': ['Hybrid multicloud',
              'Single-vendor public cloud only',
              'Bare metal-only deployment',
              'On-premises only']},
 {'id': 98,
  'section': 'B',
  'topic': 'TREND',
  'stem': 'A team wants to run short-lived code that automatically scales, never provisioning or '
          'managing servers, billed only per execution. Which trend does this describe?',
  'options': ['Serverless computing',
              'Bare metal hosting',
              'Traditional on-premises hosting',
              'Manual VM provisioning']},
 {'id': 99,
  'section': 'B',
  'topic': 'TREND',
  'stem': 'A company redesigns its monolithic application into small, independently deployable '
          'services that communicate through APIs, so each can be updated and scaled separately. '
          'Which trend is this?',
  'options': ['Microservices architecture',
              'Monolithic architecture',
              'Bare metal deployment',
              'Single-tenant architecture']},
 {'id': 100,
  'section': 'B',
  'topic': 'TREND',
  'stem': 'An application is built from the ground up to take advantage of cloud scalability, '
          'resilience, and rapid deployment (rather than migrated as-is). This is an example of:',
  'options': ['Cloud-native design',
              'Lift-and-shift migration',
              'Bare metal hosting',
              'On-premises legacy design']},
 {'id': 101,
  'section': 'B',
  'topic': 'TREND',
  'stem': 'After a suspected breach involving cloud-hosted systems, investigators must identify, '
          'preserve, analyze, and present digital evidence across distributed cloud '
          'infrastructure. Which field addresses this?',
  'options': ['Digital forensics in the cloud',
              'Serverless computing',
              'Microservices architecture',
              'Object storage design']},
 {'id': 102,
  'section': 'B',
  'topic': 'TREND',
  'stem': "A company wants to avoid being tied to one provider's proprietary services while still "
          'benefiting from best-of-breed offerings from different vendors. Which strategy offers '
          'this?',
  'options': ['Multicloud strategy',
              'Single-vendor lock-in',
              'Bare metal-only hosting',
              'On-premises-only strategy']},
 {'id': 103,
  'section': 'B',
  'topic': 'TREND',
  'stem': "Compared to traditional server-based hosting, serverless computing's primary advantage "
          'is:',
  'options': ['Automatic scaling and no server management overhead for the developer',
              'Requiring manual server patching by the developer',
              'Fixed, unchangeable capacity',
              'No billing based on usage']},
 {'id': 104,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'A cloud-hosted application slows down during peak business hours due to high demand on '
          'shared compute resources. Which challenge is this, and what mitigates it?',
  'options': ['Application performance risk — mitigated by auto-scaling and load balancing',
              'Data replication risk — mitigated by deleting logs',
              'Network security risk — mitigated by disabling firewalls',
              'Vendor lock-in — mitigated by ignoring the issue']},
 {'id': 105,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'Two departments store customer records in incompatible formats, making it hard to '
          'combine data for reporting. Which challenge is this, and what best mitigates it?',
  'options': ['Data integration risk — mitigated by standardized APIs and data formats',
              'Application performance risk — mitigated by adding more RAM only',
              'Network security risk — mitigated by encryption alone',
              'Digital forensics risk']},
 {'id': 106,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'A cloud environment is targeted by an unauthorized access attempt exploiting a weak '
          'firewall configuration. Which risk category is this, and what is the best-practice '
          'mitigation?',
  'options': ['Network security risk — mitigated by strong firewalls, encryption, and access '
              'controls',
              'Application performance risk — mitigated by disabling monitoring',
              'Data integration risk — mitigated by ignoring the incident',
              'Vendor lock-in — mitigated by more storage']},
 {'id': 107,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'A company replicates its production database to a secondary region for DR, but '
          'discovers the copy is frequently out of sync, risking data loss during failover. Which '
          'risk is this, and what best mitigates it?',
  'options': ['Data replication risk — mitigated by real-time/near-real-time synchronization with '
              'monitoring',
              'Network security risk — mitigated by turning off replication',
              'Application performance risk — mitigated by removing backups',
              'Vendor lock-in']},
 {'id': 108,
  'section': 'B',
  'topic': 'RISK',
  'stem': "A company stores sensitive files in the cloud but hasn't encrypted them at rest and "
          'lacks proper access controls, risking exposure if credentials are compromised. Which '
          'risk is this, and what mitigates it?',
  'options': ['Cloud storage risk — mitigated by encryption at rest and strict access management',
              'Application performance risk — mitigated by more compute power',
              'Data integration risk — mitigated by combining all data into one file',
              'Network security only, unrelated to storage']},
 {'id': 109,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'During incident response, a security team needs to trace exactly which user accessed a '
          'storage bucket and when, across multiple regions. This relies on:',
  'options': ['Centralized logging and monitoring supporting digital forensics',
              'Deleting all logs immediately',
              'Avoiding any audit trails',
              'Disabling access logs to save storage']},
 {'id': 110,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'A company migrating to the cloud is concerned a slow, congested network link between '
          'offices and the provider will degrade responsiveness for end users. The best mitigation '
          'is to:',
  'options': ['Optimize network routing/use a CDN and monitor performance',
              'Ignore the network entirely',
              'Remove all monitoring tools',
              'Migrate without any testing']},
 {'id': 111,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'An organization integrating a legacy on-premises system with a new cloud application '
          'experiences frequent data mismatches. Which practice would most directly reduce this '
          'risk?',
  'options': ['Using middleware or APIs with defined data validation and transformation rules',
              'Manually re-typing all data every day',
              'Disconnecting the two systems permanently',
              'Ignoring data quality checks']},
 {'id': 112,
  'section': 'B',
  'topic': 'RISK',
  'stem': "A retailer's cloud-hosted checkout system slows dramatically during a flash sale due to "
          'insufficient auto-scaling configuration. What should the team implement to mitigate '
          'future risk?',
  'options': ['Properly configured auto-scaling policies and performance testing before '
              'high-traffic events',
              'Removing the auto-scaling feature',
              'Reducing server capacity permanently',
              'Ignoring load testing']},
 {'id': 113,
  'section': 'B',
  'topic': 'RISK',
  'stem': "A healthcare provider's cloud storage was breached because default access permissions "
          'were left overly permissive. Which practice would have reduced this risk?',
  'options': ['Applying the principle of least privilege to access permissions',
              'Granting all users administrator rights',
              'Disabling all security settings',
              'Avoiding access reviews']},
 {'id': 114,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'To reduce the risk of data loss from a single point of failure during replication, a '
          'best practice is to:',
  'options': ['Replicate data across multiple availability zones or regions',
              'Store only one copy of data in one location',
              'Disable backup schedules',
              'Avoid monitoring replication status']},
 {'id': 115,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'A company wants to recover quickly if its primary cloud storage becomes corrupted or '
          'compromised. Which practice best supports this?',
  'options': ['Regular, tested backups combined with versioning',
              'Storing backups on the same corrupted volume',
              'Never testing backup restoration',
              'Disabling version history']},
 {'id': 116,
  'section': 'B',
  'topic': 'RISK',
  'stem': 'An organization notices repeated application slowdowns traced to inefficient database '
          'queries under high load. Which mitigation directly addresses this?',
  'options': ['Query optimization and caching strategies',
              'Disabling the database',
              'Removing all indexes',
              'Ignoring performance metrics']},
 {'id': 117,
  'section': 'B',
  'topic': 'ECO',
  'stem': 'A startup wants to know which cloud ecosystem role is responsible for the physical '
          "network connectivity linking their offices to the provider's data center. This role is "
          'played by the:',
  'options': ['Cloud carrier', 'Cloud auditor', 'Cloud broker', 'Cloud consumer']},
 {'id': 118,
  'section': 'B',
  'topic': 'ECO',
  'stem': 'A company wants an independent third party to verify that a chosen cloud provider meets '
          'specific security and compliance standards before signing a contract. Which role should '
          'they engage?',
  'options': ['Cloud auditor', 'Cloud carrier', 'Cloud consumer', 'Cloud reseller only']},
 {'id': 119,
  'section': 'B',
  'topic': 'ECO',
  'stem': "A company is unsure which of several providers' offerings best fits its needs, so it "
          'engages an intermediary to compare options and negotiate terms. This intermediary is '
          'acting as a:',
  'options': ['Cloud broker', 'Cloud carrier', 'Cloud auditor', 'Cloud consumer']},
 {'id': 120,
  'section': 'B',
  'topic': 'ECO',
  'stem': 'A manufacturing company signs a contract with a provider specifying guaranteed uptime '
          "of 99.9% and penalties if this isn't met. This document is known as a:",
  'options': ['Service Level Agreement (SLA)',
              'Cloud carrier agreement',
              'Data migration plan',
              'Hypervisor license']}]

TOTAL_QUESTIONS = len(QUESTIONS)